version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  api:
    build: .
    command: node server/index.js
    ports:
      - "5000:5000"
    depends_on:
      - redis

  worker:
    build: .
    command: node worker/worker.js
    depends_on:
      - redis